---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by ADMIN.
--- DateTime: 2023/3/9 15:13
---

-- 1、判断库存是否充足
-- 1.1声明参数
local voucherId = ARGV[1] -- 优惠券id
local userId = ARGV[2] -- 用户id
local orderId = ARGV[3] -- 订单id

local stockKey = 'seckill:stock:' .. voucherId -- 拼接库存key，连接符是 ..
local orderKey = 'seckill:order:' .. voucherId -- 订单key

-- 2、脚本业务
-- 2.1判断库存是否充足，判断前转化为number
if(tonumber(redis.call('get',stockKey)) <= 0) then
    -- 库存不足返回1
    return 1
end
-- 2.2判断用户是否下单
if(redis.call('sismember',orderKey,userId) == 1) then
    -- 存在则重复下单，返回2
    return 2
end
-- 3.2最后都不满足的进行优惠券库存的扣减和下单操作
redis.call('incrby',stockKey,-1) -- 扣减库存
redis.call('sadd',orderKey,userId) -- 下单保存

-- 4.经历上面校验后都有购买资格，将其发送至消息队列；将voucherId改为Id是为了对应实体类
redis.call("xadd","stream-orders","*","id",orderId,"userId",userId,"voucherId",voucherId)

return 0 -- 最后在java模块进行判断，!0皆为未下单成功操作



